### ISSUE TITLE
function signature wrong when unionfs is disabled

### ISSUE THREAD

**Issue by simbuerg** [PolyJIT/benchbuild#131]
/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/actions.py:304: RuntimeWarning: Traceback (most recent call last):
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/actions.py", line 297, in __call__
    result = a()
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/actions.py", line 33, in wrapper
    res = f(*args, **kwargs)
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/actions.py", line 331, in __call__
    result = action()
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/actions.py", line 48, in wrapper
    res = f(*args, **kwargs)
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/actions.py", line 33, in wrapper
    res = f(*args, **kwargs)
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/actions.py", line 33, in wrapper
    res = f(*args, **kwargs)
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/actions.py", line 93, in __call__
    self._action_fn()
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/utils/run.py", line 460, in wrap_in_builddir_func
    return func(self, *args, **kwargs)
  File "/scratch/pjtest/100/env/lib/python3.5/site-packages/benchbuild/projects/gentoo/gentoo.py", line 45, in download
    container.unpack_container(self.builddir)
TypeError: unpack_container() missing 1 required positional argument: 'path'

**Comment by simbuerg** [comment]
Fixed
