### ISSUE TITLE
Slurm running one project crashes

### ISSUE THREAD

**Issue by vulder** [PolyJIT/benchbuild#149]
Call + stack trace
```
$ virt_vara/bin/benchbuild slurm -E RegionAnalyser -P minperf1 Experiment: RegionAnalyser
Traceback (most recent call last):
  File "virt_vara/bin/benchbuild", line 11, in <module>
    sys.exit(main())
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/benchbuild/driver.py", line 48, in main
    return PollyProfiling.run(*args)
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/plumbum/cli/application.py", line 505, in run
    inst, retcode = subapp.run(argv, exit = False)
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/plumbum/cli/application.py", line 500, in run
    retcode = inst.main(*tailargs)
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/benchbuild/slurm.py", line 104, in main
    exp = exp_cls(project_names)
  File "<attrs generated init a0c5157b1b300b6bd4b44d32b3f757f4d931c9ab>", line 13, in __init__
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/benchbuild/experiment.py", line 97, in default_id
    if self.name in cfg_exps:
TypeError: unhashable type: 'list'
```

**Comment by simbuerg** [comment]
Fixed in 3.0 releases
