### ISSUE TITLE
Slurm running group crashes

### ISSUE THREAD

**Issue by vulder** [PolyJIT/benchbuild#150]
Call + Stack:
```
$ virt_vara/bin/benchbuild slurm -E RegionAnalyser -G Perf
Experiment: RegionAnalyser
Traceback (most recent call last):
  File "virt_vara/bin/benchbuild", line 11, in <module>
    sys.exit(main())
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/benchbuild/driver.py", line 48, in main
    return PollyProfiling.run(*args)
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/plumbum/cli/application.py", line 505, in run
    inst, retcode = subapp.run(argv, exit = False)
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/plumbum/cli/application.py", line 500, in run
    retcode = inst.main(*tailargs)
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/site-packages/benchbuild/slurm.py", line 108, in main
    exp.id))
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/scratch/sattlerf/VaRA/virt_vara/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'UUID'
```

**Comment by simbuerg** [comment]
Fixed in 3.0 releases
