### ISSUE TITLE
Crashing BB during config creation

### ISSUE THREAD

**Issue by vulder** [PolyJIT/benchbuild#152]
BB crashed when creating a config file with -s
```bash
benchbuild run -s
```
leads to
```
Traceback (most recent call last):
  File "/home/vulder/.local/bin//benchbuild", line 11, in <module>
    sys.exit(main())
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/driver.py", line 48, in main
    return PollyProfiling.run(*args)
  File "/home/vulder/.local/lib64/python3.5/site-packages/plumbum/cli/application.py", line 505, in run
    inst, retcode = subapp.run(argv, exit = False)
  File "/home/vulder/.local/lib64/python3.5/site-packages/plumbum/cli/application.py", line 500, in run
    retcode = inst.main(*tailargs)
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/run.py", line 198, in main
    pg_bar.start()
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/progress.py", line 67, in start
    super(ProgressBar, self).start()
  File "/home/vulder/.local/lib64/python3.5/site-packages/plumbum/cli/progress.py", line 49, in start
    self.iter = iter(self.iterator)
TypeError: 'NoneType' object is not iterable

```

**Comment by simbuerg** [comment]
Really fixed by 82d35866d
