### ISSUE TITLE
yaml repr exception during run Action

### ISSUE THREAD

**Issue by vulder** [PolyJIT/benchbuild#154]
It looks like the yaml representer cannot handle the UUID

```Experiment terminates because we got an exception:
Traceback (most recent call last):
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 457, in __call__
    result = a()
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 82, in wrapper
    res = func(*args, **kwargs)
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 120, in wrapper
    res = func(self, *args, **kwargs)
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 501, in __call__
    results.extend(action())
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 139, in wrapper
    res = f(*args, **kwargs)
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 82, in wrapper
    res = func(*args, **kwargs)
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 82, in wrapper
    res = func(*args, **kwargs)
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 120, in wrapper
    res = func(self, *args, **kwargs)
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/actions.py", line 205, in __call__
    self.action_fn()
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/run.py", line 556, in wrap_in_builddir_func
    return func(self, *args, **kwargs)
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/run.py", line 744, in wrap_store_config
    CFG.store(os.path.join(p, ".benchbuild.yml"))
  File "/home/vulder/.local/lib64/python3.5/site-packages/benchbuild/utils/settings.py", line 188, in store
    default_flow_style=False)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/__init__.py", line 217, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/__init__.py", line 196, in dump_all
    dumper.represent(data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 205, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/vulder/.local/lib64/python3.5/site-packages/yaml/representer.py", line 229, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', UUID('72064b4e-aa23-4016-8497-b16974acac50'))
```

**Comment by simbuerg** [comment]
Can you send me the the section 'experiments' form your .benchbuild.yml ?
