### ISSUE TITLE
TypeError: NoneType not callable

### ISSUE THREAD

**Issue by vulder** [PolyJIT/benchbuild#40]
tests: 2mm, lammps, 7z, postgres, povray, ffmpeg, floyd-warshall, rasdaman, sdcc, gesummv, x264

PHASE 'run' 2mm OK
libpprof: 0 tid 6408 events - 0.146667 MB
Exception ignored in: <bound method SessionManager.__del__ of <pprof.utils.schema.SessionManager object at 0x7fbdd55e74e0>>
Traceback (most recent call last):
  File "/scratch/pjtest/pj-papi/pprof/lib/python3.4/site-packages/pprof/utils/schema.py", line 270, in **del**
  File "/scratch/pjtest/pj-papi/pprof/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 826, in close
  File "/scratch/pjtest/pj-papi/pprof/lib/python3.4/site-packages/sqlalchemy/pool.py", line 871, in close
  File "/scratch/pjtest/pj-papi/pprof/lib/python3.4/site-packages/sqlalchemy/pool.py", line 747, in _checkin
TypeError: 'NoneType' object is not callable

**Comment by simbuerg** [comment]
Somehow the database connection object seems to have vanished already, weird.

**Comment by simbuerg** [comment]
Fixed.
