### ISSUE TITLE
LOG.error causes an exception if the path is too long

### ISSUE THREAD

**Issue by J03D03** [PolyJIT/benchbuild#426]
# Description

Running `benchbuild` from `/home/user/vara/vara-root/benchbuild` causes an exception.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
[...]
   File "/home/user/.local/lib/python3.8/site-packages/benchbuild/environments/service_layer/unit_of_work.py", line 131, in _rollback
    buildah.run(buildah.bb_buildah('rm')[container.container_id])
  File "/home/user/.local/lib/python3.8/site-packages/benchbuild/environments/adapters/common.py", line 43, in wrapped_cmd
    LOG.error(runroot.__to_env_var__(), __MSG_SHORTER_PATH_REQUIRED)
Message: 'BB_CONTAINER_RUNROOT'
Arguments: ('needs to be shorter than 50 chars.',)
```

Commands that cause this crash (+ output):
- `benchbuild -vv container run -E GenerateBlameReport gzip`  ([benchbuild50chars.log](https://github.com/PolyJIT/benchbuild/files/7015676/benchbuild50chars.log))
- `vara-container prepare-slurm` ([gt50chars.log](https://github.com/PolyJIT/benchbuild/files/7015621/gt50chars.log))

Tested with [f-vara-run](https://github.com/se-sic/VaRA-Tool-Suite/tree/f-vara-run) (`04625239cdd152063ae70d874dc2a474cd4ac96f`)

**Comment by simbuerg** [comment]
Thanks :-) Seems someone (me) forgot how to properly use python's log functions :-)
