### ISSUE TITLE
Iterable import from collections broken on python 3.10

### ISSUE THREAD

**Issue by Ramdambo** [PolyJIT/benchbuild#465]
In Python 3.10, [all aliases to abstract base classes were removed from the `collections` module](https://docs.python.org/3/whatsnew/3.10.html).

I think they can be found in `typing` now.

**Comment by Ramdambo** [comment]
Relevant error message when executing `clang -v`

```
clang version 12.0.0 (git@github.com:se-passau/vara-llvm-project.git abb8fdaf526b6da85bad49527f6e7a5d23810a84)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/daniel/vara/vara-root/tools/VaRA/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Traceback (most recent call last):
  File "/home/daniel/vara/vara-root/benchbuild/results/JustCompile/xz-c_projects@2f4281a100/clang", line 52, in <module>
    sys.exit(main(sys.argv))
  File "/home/daniel/vara/vara-root/benchbuild/results/JustCompile/xz-c_projects@2f4281a100/clang", line 45, in main
    run_info = PROJECT.compiler_extension(
  File "/home/daniel/vara/varats-venv/lib/python3.10/site-packages/benchbuild/extensions/run.py", line 73, in __call__
    return self.call_next(
  File "/home/daniel/vara/varats-venv/lib/python3.10/site-packages/benchbuild/extensions/base.py", line 63, in call_next
    results = ext(*args, **kwargs)
  File "/home/daniel/vara/varats-root/varats-core/varats/experiment/wllvm.py", line 84, in __call__
    return self.call_next(wllvm, *args, **kwargs)
  File "/home/daniel/vara/varats-venv/lib/python3.10/site-packages/benchbuild/extensions/base.py", line 69, in call_next
    if isinstance(results, c.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'
```
